# Generated by Django 2.2.4 on 2019-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyfaq',
            name='web_active',
            field=models.BooleanField(default=True, verbose_name='Web Active'),
        ),
        migrations.AlterField(
            model_name='pyfaq',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
