# Generated by Django 2.2.4 on 2019-09-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190914_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyfaq',
            name='web_active',
        ),
        migrations.AddField(
            model_name='pywpayment',
            name='web_active',
            field=models.BooleanField(default=True, verbose_name='Web Active'),
        ),
    ]
