# Generated by Django 2.2.4 on 2019-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190914_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('value', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
