# Generated by Django 2.2.4 on 2019-09-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190914_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pycompany',
            name='giro',
        ),
        migrations.AddField(
            model_name='pycompany',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
