# Generated by Django 2.2.4 on 2019-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190914_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycompany',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
