# Generated by Django 2.2.4 on 2019-09-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pycompany_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycompany',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pycompany',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
