# Generated by Django 2.2.4 on 2019-09-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190915_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PyPaymentMethod',
        ),
    ]
