# Generated by Django 2.2.4 on 2019-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_pyvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypage',
            name='keywords',
            field=models.CharField(blank=True, max_length=20, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='pypost',
            name='keywords',
            field=models.CharField(blank=True, max_length=20, verbose_name='Keywords'),
        ),
    ]
