# Generated by Django 2.2.4 on 2019-09-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_pyuom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyuom',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyProductCategoryUOM'),
        ),
        migrations.AddField(
            model_name='pyuom',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ratio'),
        ),
        migrations.AddField(
            model_name='pyuom',
            name='rouding',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='Ratio'),
        ),
        migrations.AddField(
            model_name='pyuom',
            name='type',
            field=models.CharField(choices=[('bigger', 'Bigger'), ('reference', 'Reference'), ('smaller', 'Smaller')], default='consu', max_length=64, verbose_name='type'),
        ),
    ]
