# Generated by Django 2.2.4 on 2019-09-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20190915_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproduct',
            name='uom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyUom'),
        ),
    ]
