# Generated by Django 2.2.4 on 2019-09-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_pytax'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproduct',
            name='tax_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyTax'),
        ),
    ]
